config/routes.rb
Rails.application.routes.draw do
  resources :spents
  resources :users

  get "up" => "rails/health#show", as: :rails_health_check

  root 'users#pagPrincipal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/spent.rb
class Spent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spents_controller.rb
class SpentsController < ApplicationController

    def index
        @spents = Spent.all
    end

    def new  
    end

    def show
        @spent = Spent.find(params[:id])
    end

    def edit
        @id = params[:id]
    end

    def update
        @spent = Spent.find(params[:id])

        
        @spent.monto = params[:spents][:monto]
        @spent.descripcion = params[:spents][:descripcion]
        @spent.boleta_img = params[:spents][:boleta_img]
        @spent.estado = params[:spents][:estado]
        @spent.id_user = params[:spents][:id_user]

        @spent.save

        redirect_to "/spents/#{params[:id]}"

    end

    def destroy
        @spent = Spent.find(params[:id])
        @spent.destroy

        redirect_to "/spents"
    end

    def create
        @spents = Spent.new

        
        @spents.monto = params[:spents][:monto]
        @spents.descripcion = params[:spents][:descripcion]
        @spents.boleta_img = params[:spents][:boleta_img]
        @spents.estado = "en espera"
        @spents.id_user = params[:spents][:id_user]

        @spents.save

        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def pagPrincipal
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @spents = Spent.all
    end

    def new
    end

    def create
        @user = User.new

        @user.nombreUsuario = params[:users][:name]
        @user.password = params[:users][:password]

        @user.save

        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spents_helper.rb
module SpentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyLoopin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spents/edit.html.erb
<h1> Editar Gasto </h1>

    <form action="/spents/<%= @id %>" method="post">

        <input type="hidden" name="_method" value="PATCH">

        <div>

            <label for="monto">Monto:</label>
            <input type="number" name="spents[monto]" id="monto">

            <label for="descripcion">Descripcion:</label>
            <input type="text" name="spents[descripcion]" id="descripcion">

            <label for="boleta_img">boleta_img:</label>
            <input type="text" name="spents[boleta_img]" id="boleta_img">

            <label for="user_id">User_id:</label>
            <input type="number" name="spents[id_user]" id="user_id">
            
            <label for="dwarfs">Selecciona el estado:</label>
            <select multiple name="spents[estado]" id="drawfs" >
                <option>Pendiente</option>
                <option>Aprobado</option>
                <option>Rechazado</option>
            </select>  

        </div>

        <p> <input type="submit" value="Aceptar"> </p>  	
        
    </form>

<p>
    <a href="/">
        <button type="button">Volver al inicio</button>
    </a>
</p>

app/views/spents/index.html.erb
<h1>
    Gastos Existentes
</h1>

<% @spents.each do |spent| %>
    <div>
        <p> Monto: <%= spent.monto%> </p>
        <p> Descripcion: <%= spent.descripcion %> </p>
        <p> Imagen: <%= spent.boleta_img%> </p>
        <p> Estado del gasto: <%= spent.estado %> </p>
        <p><%= link_to "Ver gasto", spent%></p>
    </div>
<% end %>

<a href="/spents/new">
    <button type="button"> Ingresar nuevo gasto </button>
</a>

app/views/spents/new.html.erb
<h1> Crear Nuevo gasto </h1>

<form action="/spents" method="post">

    
    <label for="monto">Monto:</label>
    <input type="number" name="spents[monto]" id="monto">

    <label for="descripcion">Descripcion:</label>
    <input type="text" name="spents[descripcion]" id="descripcion">

    <label for="boleta_img">boleta_img:</label>
    <input type="text" name="spents[boleta_img]" id="boleta_img">

    <label for="user_id">User_id:</label>
    <input type="number" name="spents[user_id]" id="user_id">
    
    <input type="submit" value="Crear nuevo gasto">	

</form>

app/views/spents/show.html.erb
<h1>
    Gasto Seleccionado
</h1>

    <div>
        <p> <%= @spent.monto%> </p>
        <p> <%= @spent.descripcion %> </p>
        <p> <%= @spent.boleta_img%> </p>
        <p> <%= @spent.estado %> </p>

        <div>
            <%= link_to "Editar", "/spents/#{@spent.id}/edit"%>
            <%= link_to "Eliminar", spent_path(@spent), method: :delete%>
        </div>

    </div>


<p></p>
<a href="/spents/new">
    <button type="button"> Ingresar nuevo gasto </button>
</a>

<a href="/">
    <button type="button"> Volver al inicio </button>
</a>

app/views/users/new.html.erb
<h1> Crear Nuevo usuario </h1>

<form action="/users" method="post">

    <label for="name">Nombre:</label>
    <input type="text" name="users[name]" id="name">

    <label for="password">Contrasenia:</label>`
    <input type="text" name="users[password]" id="password">
    
    <input type="submit" value="Crear usuario">	

</form>

app/views/users/pagPrincipal.html.erb
<h1>
    Bienvenidos!! Pagina Principal
</h1>

<% @users.each do |user| %>
    <div>
        <p> ID: <%= user.id%> </p>
        <p> Nombre del usuario: <%= user.nombreUsuario%> </p>
        <p> Contrasenia: <%= user.password%> </p>

        <p><%= link_to "Ver usuario", user%></p>
    </div>
<% end %>

<a href="/users/new">
    <button type="button"> Ingresar nuevo usuario </button>
</a>

<a href="/spents">
    <button type="button"> Gastos</button>
</a>

app/views/users/show.html.erb
<h1>
    Usuario Seleccionado
</h1>

<div>
    <p> ID: <%= @user.id%> </p>
    <p> Nombre del usuario: <%= @user.nombreUsuario%> </p>
    <p> Contrasenia: <%= @user.password%> </p>
</div>


<h1>
    Total gastos rendidos
</h1>

<% @spents.each do |spent| %>
        <div>
            <p> Monto: <%= spent.monto %> </p>
            <p> Descripcion: <%= spent.descripcion %> </p>
            <p> Imagen: <%= spent.boleta_img %> </p>
            <p> Estado del gasto: <%= spent.estado %> </p>
            <p><%= link_to "Ver gasto", spent %></p>
        </div>
<% end %>

<h1>
    Total gastos aprobados
</h1>

<% @spents.each do |spent| %>
    <% if spent.estado == "Aprobado" %>
        <div>
            <p> Monto: <%= spent.monto %> </p>
            <p> Descripcion: <%= spent.descripcion %> </p>
            <p> Imagen: <%= spent.boleta_img %> </p>
            <p> Estado del gasto: <%= spent.estado %> </p>
            <p><%= link_to "Ver gasto", spent %></p>
        </div>
    <% end %>
<% end %>

<h1>
    Total gastos rechazados
</h1>

<% @spents.each do |spent| %>
    <% if spent.estado == "Rechazado" %>
        <div>
            <p> Monto: <%= spent.monto %> </p>
            <p> Descripcion: <%= spent.descripcion %> </p>
            <p> Imagen: <%= spent.boleta_img %> </p>
            <p> Estado del gasto: <%= spent.estado %> </p>
            <p><%= link_to "Ver gasto", spent %></p>
        </div>
    <% end %>
<% end %>



<a href="/">
    <button type="button"> Volver al inicio </button>
</a>